import type { Metadata } from "next";
// import { Dongle } from "next/font/google";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Playpro Academy",
  description: "Generated by Playpro",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: "400"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${poppins.className}`}
      >
        {children}
        <Toaster position="top-right"/>
      </body>
    </html>
  );
}
