import type { Metadata } from "next";
import { Dongle } from "next/font/google";
import "./globals.css";

const dongle = Dongle({
  weight: "400",
  subsets: ["latin"],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Playpro Academy",
  description: "Generated by Playpro",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
